<?php

namespace Fa\SiteBundle\Entity\Repository;

/**
 * CursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursoRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function listarTodosVinculados($limite = null, $tipoCurso){
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->distinct()
                ->innerJoin('FaSiteBundle:InfoCurso', 'ic', 'WITH', 'c.id = ic.curso')
                ->andWhere('c.tipoCurso = '.$tipoCurso)
                ->addOrderBy('c.nome', 'ASC');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
}
