<?php

namespace Fa\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DescricaoCursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescricaoCursoRepository extends EntityRepository
{
}
