<?php

namespace Fa\SiteBundle\Entity\Repository;

/**
 * TipoCursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoCursoRepository extends \Doctrine\ORM\EntityRepository
{
}
